### ISSUE TITLE
Ever since you added the tray icon, I cannot compile with the `cl` command line tool

### ISSUE THREAD

**Issue by charlesmilette** [ethanhs/TranslucentTB#11]
This command used to work, now it only gives me this:

```
C:\Users\Charles\Git\TranslucentTB\TranslucentTB>cl main.cpp /EHsc /Fe"TranslucentTb" /link /subsystem:windows user32.lib
Compilateur d'optimisation Microsoft (R) C/C++ version 19.00.24213.1 pour x64
Copyright (C) Microsoft Corporation. Tous droits réservés.

main.cpp
main.cpp(220): error C2664: 'HWND FindWindowA(LPCSTR,LPCSTR)' : impossible de convertir l'argument 1 de 'const wchar_t [23]' en 'LPCSTR'
main.cpp(220): note: Les types pointés n'ont aucun rapport entre eux ; conversion nécessitant reinterpret_cast, cast de style C ou cast de style fonction
main.cpp(274): error C2660: 'wcscpy_s' : la fonction ne prend pas 2 arguments
main.cpp(292): error C2440: '=' : impossible de convertir de 'const wchar_t [14]' en 'LPCSTR'
main.cpp(292): note: Les types pointés n'ont aucun rapport entre eux ; conversion nécessitant reinterpret_cast, cast de style C ou cast de style fonction
main.cpp(303): error C2664: 'HWND CreateWindowExA(DWORD,LPCSTR,LPCSTR,DWORD,int,int,int,int,HWND,HMENU,HINSTANCE,LPVOID)' : impossible de convertir l'argument 2 de 'const wchar_t [14]' en 'LPCSTR'
main.cpp(303): note: Les types pointés n'ont aucun rapport entre eux ; conversion nécessitant reinterpret_cast, cast de style C ou cast de style fonction
main.cpp(317): error C2664: 'HWND FindWindowExA(HWND,HWND,LPCSTR,LPCSTR)' : impossible de convertir l'argument 3 de 'const wchar_t [23]' en 'LPCSTR'
main.cpp(317): note: Les types pointés n'ont aucun rapport entre eux ; conversion nécessitant reinterpret_cast, cast de style C ou cast de style fonction
```

I removed the error generated by the edits I am working on right now.

**Comment by ethanhs** [comment]
That is likely because it cannot find the menu resource in TranslucentTB.rc. I believe you need to call `rc` on the rc file, and modify your cl command line to include the generated .res file.

**Comment by charlesmilette** [comment]
Most of the errors do not relate to this. They generally are: `unable to convert argument from "const wchar_t" to "LPCSTR"`

I could fix it by appending L to all the strings, but I don't know why you would be able to compile without them if I am not

**Comment by ethanhs** [comment]
LPCSTR is a long pointer to a c str, its basically char*, and thus not compatible with wchar, which is a wide character. Did you change the function names? If you did, none of the strings should be prefixed with L (since this makes them a wchar_t literal) and you must replace all of the wc* functions with their char equivalents (eg wcscpy_s->strcpy_s)

**Comment by ethanhs** [comment]
@charlesmilette did you get it to compile? Also, may I ask why you changed the functions to ascii?

**Comment by charlesmilette** [comment]
Got it.
I had to add
```
#define UNICODE
#define _UNICODE
```
 at the header.
