### ISSUE TITLE
Repaint taskbar in event window is maximized

### ISSUE THREAD

**Issue by whatHappenedToBrendanFraser** [ethanhs/TranslucentTB#24]
Possible launch option

**Comment by ethanhs** [comment]
Hi! May I ask why you would want this? Would you want the blur/transparency to be turn off while this window is maximized?

**Comment by olliethepikachu** [comment]
If it is as @ethanhs is saying (eg blurry when window is maximised and transparent otherwise) I am currently working on an implementation of that and will submit a PR to `develop` when it's done.

**Comment by charlesmilette** [comment]
In that case, I'd suggest to add it as a "Auto" in the context menu. I'll suggest once #24 is merged, we wait so that @ethanhs does a refactor without having to care about new changes constantly coming in. Once the refactor is done, you could start working on that and me on the configuration file.

**Comment by whatHappenedToBrendanFraser** [comment]
@ethanhs It looks out of place having the taskbar transparent when a window is maximized, where as when windows are floating it looks like an open space. Just a preference, and it should be a launch option if implemented.

**Comment by ethanhs** [comment]
@whatHappenedToBrendanFraser definitely support this idea!

**Comment by olliethepikachu** [comment]
I'm working on this; it also includes the use of a map for storing `HWND`s, and @ethanhs has said he'll wait until it's completed until his refactor. I should submit a PR to `develop` later today. Would calling it `dynamic` work?





On Sat, Jan 14, 2017 at 5:16 AM +0800, "Ethan" <notifications@github.com> wrote:












@whatHappenedToBrendanFraser definitely support this idea!

**Comment by ethanhs** [comment]
resolved in #33
