### ISSUE TITLE
Theme Cortana search bar

### ISSUE THREAD

**Issue by ente3000** [ethanhs/TranslucentTB#29]
I'm using Windows 10 (10.0.14393) and the Cortana bar isn't colored/themed.

Screenshots:
![Start menu closed](https://cloud.githubusercontent.com/assets/8181990/21927975/951da512-d988-11e6-94ed-85e09c682bdf.png)
![Start menu opened](https://cloud.githubusercontent.com/assets/8181990/21927976/952017fc-d988-11e6-8eec-1a0de9821677.png)

Except for that, everything looks and works just fine!

**Comment by olliethepikachu** [comment]
Unfortunately the Cortana bar can't be themed like the others. You can replace the bar with a Cortana icon though, which works.

**Comment by ente3000** [comment]
Oh, alright. Thanks for the answer anyway!
