### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by ethanhs** [ethanhs/TranslucentTB#3]
This should be in the form:

```
blur=1
setting=[num]
# comments would be bonus
```

Using iostream and std::string, this should be easy enough.

These setting should be passed to a state struct that holds the settings while the program is running (since these settings can be changed via command line, or the tray).

**Comment by charlesmilette** [comment]
There's a whole list of APIs available for easy manipulating of an .INF file

https://msdn.microsoft.com/en-us/library/aa377385.aspx

**Comment by ethanhs** [comment]
That is true, but it appears that API is for install/setup applications...

**Comment by charlesmilette** [comment]
[What about INI instead?](https://msdn.microsoft.com/en-us/library/ms724353.aspx)

**Comment by ethanhs** [comment]
That will do well.

**Comment by ethanhs** [comment]
Also, we can chat on gitter if you want https://gitter.im/TranslucentTB/Lobby
And there is the corresponding [Write function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms725501(v=vs.85).aspx)

**Comment by ethanhs** [comment]
Resolved in #31
