### ISSUE TITLE
Windows 8.1?

### ISSUE THREAD

**Issue by Skrell** [ethanhs/TranslucentTB#32]
Any chance of making this work with 8.1 too?

**Comment by charlesmilette** [comment]
I'm not even sure if `SetWindowCompositionAttribute` exists in Windows 8

**Comment by olliethepikachu** [comment]
Unfortunately this used APIs which are only available in Windows 10 (Microsoft included them to do the aero start menu).

**Comment by MrAksel** [comment]
I don't think we have an 8.1 machine to test on either, so it would be hard even if it was possible :/

**Comment by olliethepikachu** [comment]
@charlesmilette No, the API call doesn't exist.

**Comment by ethanhs** [comment]
Nope, won't work sorry. I have a Windows 8.1 machine, but I don't think it is worth it. I know this is new.
