### ISSUE TITLE
Multi-monitor

### ISSUE THREAD

**Issue by WindfallProphet** [ethanhs/TranslucentTB#34]
It only seems to be affecting the taskbar on one of my monitors. Figured this was a bug since you mentioned that multi-monitor was supported

**Comment by olliethepikachu** [comment]
Hmmm... which version of the .exe are you using?

**Comment by ethanhs** [comment]
@WindfallProphet if you could, check that you are using the latest [(you can get that here)](https://github.com/ethanhs/TranslucentTB/releases/download/2017.2/TranslucentTB.2017.2.zip). Also, if you could tell us more about your setup (What version of Windows are you on?) that would be appreciated.

**Comment by ski7777** [comment]
Just tried with Windows 10 x64 Insider Preview on Build 10007. Dual monitor setup is working fine.

Raphael

**Comment by ethanhs** [comment]
I'm going to close this, but if people have future issues, please don't hesitate to reopen/leave a comment.
