### ISSUE TITLE
The taskbar keeps flashing

### ISSUE THREAD

**Issue by Adiwon** [ethanhs/TranslucentTB#42]
In blur mode everything is fine, but when I choose clear mode the taskbar keeps flashing, or more accurately, keeps switching between blur and clear mode rapidly.
---
 I restarted the program then problem resolved. Still hope that what I reported before could be helpful.

**Comment by ethanhs** [comment]
This is caused when you have multiple copies of the program running. This will be solved in V3, as it will only allow one copy to run at a time. For now you will need to close one copy.
