### ISSUE TITLE
Update readme.md to demo use of software

### ISSUE THREAD

**Issue by Gunny123** [ethanhs/TranslucentTB#8]
I'd like to submit a gifv or screenshot/image to demonstrate what this simple piece of software does for Windows 10 task bars. 

As well as write up instructions that better communicate how to automatically have Windows load the app on startup. (Some people forget that they need to have hidden files turned on to see the AppData folder) Just so users don't have to scroll through reddit comments as much. 

Thoughts? 

Really enjoying what this has done for my desktop btw.

**Comment by ethanhs** [comment]
Yes, when I have the 2017.2 release out, as part of the write up I am going to include a screenshot of examples. One thing that might be nice is a video (I would be happy to link to) walking through the usage.

I also might [add a script to automatically make said shortcut](http://superuser.com/a/836818).

**Comment by Gunny123** [comment]
Should I submit a PR with a gfycat link or imgur gifv? I can whip up something quick. Let me know if you have any guidelines you'd like to follow.

**Comment by ethanhs** [comment]
I think an imgur gifv. I would prefer for some textual annotations to the gifv if you could add that. I can provide you an early build of 2017.2 (releasing in 6 hours) so that you can make the gifv based on that. I have a bit more work to do on the tray, but when I'm back in front of my computer I can finish that up. Could I send it to you in an hour? I'll post to this thread.

**Comment by Gunny123** [comment]
> I think an imgur gifv.

Sounds good.

> Could I send it to you in an hour? I'll post to this thread.

Sure thing

**Comment by ethanhs** [comment]
Hey, sorry but it looks like it could be a bit before I get back in front of the computer, I will let you know when I have a build. If the tutorial doesn't happen at launch its not the end of the world.

**Comment by Gunny123** [comment]
No problem. Take time.

**Comment by charlesmilette** [comment]
In the config GUI I am making, it would be rather easy to add this feature instead than having a separate script.

If you plan to add a tray and context menu, you could also simply add a toggle in it to disable and enable autorun

**Comment by ethanhs** [comment]
@charlesmilette sounds good. also I am about to finally get back in front of computer and will work on the tray icon.

**Comment by Gunny123** [comment]
I like @charlesmilette idea of implementing directly within the GUI instead of a wordy instructional method. Much cleaner.

**Comment by ethanhs** [comment]
@Gunny123 sorry I took so long.  [here you go](https://1drv.ms/u/s!ArOBgkAuJuXmsEQi5kYFugjWcmP0). I'll probably post release 11 Eastern Time, so if you put your PR in before then, I will be happy to merge it.

**Comment by Gunny123** [comment]
@ethanhs Shoot, I am at work right now, I can have something by end of day though

**Comment by ethanhs** [comment]
Hm, gonna release before then. No problem, when you do get it, make a PR to develop and I should merge it in pretty quick. Thanks!

**Comment by Gunny123** [comment]
Are you not going with the transparent task bar? Instead, opting for translucent?

**Comment by ethanhs** [comment]
It has options for both. There is a tray and you can toggle it (see readme.md)

**Comment by Gunny123** [comment]
Just noticed. My b.

**Comment by ethanhs** [comment]
np :) cheers!

**Comment by ethanhs** [comment]
@Gunny123 feel free to make a PR to master with a GIFV whenever you want. I'd love to have this example.

**Comment by Gunny123** [comment]
I forgot NVIDIA's Instant Replay could record the desktop. I'm editing it right now. I'll post a link to gfycat before going to imgur so I can get some feedback from you.

**Comment by MrAksel** [comment]
The color feature isn't a part of the GUI yet, but you can change the color of the taskbar as well if you launch it from the command line with a --tint parameter. It's documented in usage.md, so you can look there if you want to include that in the gif! Looks great btw.

**Comment by Gunny123** [comment]
> The color feature isn't a part of the GUI yet

I'll update when added for sure.

**Comment by ethanhs** [comment]
@Gunny123 thanks! I will put that link in when I next update the README.

**Comment by Gunny123** [comment]
@ethanhs [GIFV](http://i.imgur.com/Y4FUeRt.gifv)

**Comment by ethanhs** [comment]
Thanks, I think I will link to the Gfycat, higher res.

**Comment by Gunny123** [comment]
@ethanhs Not to be too technical, but I did compress the original video from 25MB down to 1.47MB using HandBrake. If you want the original as well let me know.

**Comment by ethanhs** [comment]
No, I think the Gfycat is great, thanks!

**Comment by ethanhs** [comment]
I added this. Thanks @Gunny123 !
